ci(husky): re-enable pre-commit hooks

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,5 @@
 # # Exit on error
-# set -e
+set -e
 
 echo "📝 Running formatting check..."
 npm run format || {
@@ -13,18 +13,18 @@ npm run lint || {
     exit 1
 }
 
-# echo "📝 Running type check..."
-# npm run type-check || {
-#     echo "❌ Type check failed. Please fix the type errors before committing."
-#     exit 1
-# }
+echo "📝 Running type check..."
+npm run type-check || {
+    echo "❌ Type check failed. Please fix the type errors before committing."
+    exit 1
+}
 
 
-# echo "📝 Running unit tests..."
-# npm run test || {
-#     echo "❌ Unit tests failed. Please fix the unit tests before committing."
-#     exit 1
-# }
+echo "📝 Running unit tests..."
+npm run test || {
+    echo "❌ Unit tests failed. Please fix the unit tests before committing."
+    exit 1
+}
 
 git add .
 
